### ISSUE TITLE
Update stable version in repo from 0.0.0 to 0.6.3

### ISSUE THREAD

**Issue by GermanBluefox** [Bannsaenger/ioBroker.x-touch#29]
# Think about adding version 0.6.3 to stable repository.
**Version**: stable=**0.0.0** (0 days old) => latest=**0.6.3** (119 days old)
**Installs**: stable=**0** (0%), latest=**2** (50%), total=**4**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json)

**Comment by Bannsaenger** [comment]
Pull request done
